apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teams-api-ingress
  namespace: teams-api
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/headers.accesscontrolallowmethods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    traefik.ingress.kubernetes.io/headers.accesscontrolalloworigin: "*"
    traefik.ingress.kubernetes.io/headers.accesscontrolallowheaders: Content-Type,Authorization,X-Requested-With
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: teams-api.127.0.0.1.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: teams-api-service
            port:
              number: 4200
  - host: teams-api.fd60-627a-a42b-42d3-861a-6987-3179-4d87.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: teams-api-service
            port:
              number: 4200              
