apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-teams-api
  namespace: argocd
spec:
  destination:
    namespace: teams-api
    server: https://kubernetes.default.svc
  project: engineering-platform
  source:
    path: argo/teams-api
    repoURL: https://github.com/joengineering/eng-platform
    targetRevision: jo/final
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
